# Generated by Django 5.1.15 on 2026-03-15 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('heavy_equipment', 'Heavy Equipment'), ('medical', 'Medical'), ('fleet', 'Fleet'), ('industrial', 'Industrial')], max_length=20)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacture_year', models.IntegerField()),
                ('base_monthly_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('per_hour_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('leased', 'Leased'), ('maintenance', 'Maintenance'), ('remarketed', 'Remarketed')], default='available', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('total_hours_logged', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_base_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('per_hour_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='lease_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='originations.asset')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(default=dict)),
                ('validation_issues', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('pages_analyzed', models.IntegerField(default=0)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_analysis', to='originations.leasecontract')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
