# Generated by Django 5.1.15 on 2026-03-15 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('originations', '0001_initial'),
        ('servicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('spike', 'Billing Spike'), ('duplicate', 'Potential Duplicate'), ('zero_usage', 'Zero Usage Billed'), ('outlier', 'Statistical Outlier'), ('dormant', 'Dormant Asset Billed')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='servicing.invoice')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('chart_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_probability', models.FloatField(default=0.0)),
                ('days_to_predicted_failure', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(default='safe', max_length=10)),
                ('top_signals', models.JSONField(default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('predicted_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_prediction', to='originations.asset')),
            ],
            options={
                'ordering': ['-failure_probability'],
            },
        ),
        migrations.CreateModel(
            name='RemarketingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_action', models.CharField(choices=[('sell_now', 'Sell Now'), ('hold', 'Hold'), ('refurbish', 'Refurbish then Sell'), ('re_lease', 'Re-Lease')], default='hold', max_length=20)),
                ('sell_price_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('refurbish_cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_roi_12m', models.FloatField(default=0.0)),
                ('roi_curve', models.JSONField(default=list)),
                ('rationale', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remarketing_recommendation', to='originations.asset')),
            ],
            options={
                'ordering': ['-net_roi_12m'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0)),
                ('risk_band', models.CharField(default='low', max_length=10)),
                ('top_drivers', models.JSONField(default=list)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='originations.leasecontract')),
            ],
            options={
                'ordering': ['-probability'],
            },
        ),
    ]
